WALK_UP = 4
WALK_DOWN = 3
WALK_RIGHT = 2
WALK_LEFT = 1

NO_OP = 0

INTERACT_PRIMARY = 5
INTERACT_PICK_UP_SPECIAL = 6

WALK_ACTIONS = [WALK_UP, WALK_DOWN, WALK_RIGHT, WALK_LEFT]
INTERACT_ACTIONS = [INTERACT_PRIMARY, INTERACT_PICK_UP_SPECIAL]
ACTIONS = [NO_OP, WALK_LEFT, WALK_RIGHT, WALK_DOWN, WALK_UP, INTERACT_PRIMARY, INTERACT_PICK_UP_SPECIAL]
